### PR TITLE
Removed custom conda_ensure_channels setting

### PR DESCRIPTION
**Pull request by hepcat72**
Resolves issue #5

### CODE REVIEW

**Review by lparsons — APPROVED** [review]
lgtm

**Comment by lparsons** [comment]
We should probably push this out to galaxy-dev now and galaxy production as soon as we're comfortable with a restart, just to make sure we get it tested before we forget we made the change. 😉

**Comment by hepcat72** [comment]
Does an ansible restart re-push?

**Comment by lparsons** [comment]
> Does an ansible restart re-push?

No, but I think adding `--tag restart, config` would push the config changes and restart only.

**Pull request merged**
